In [30]:
import pandas as pd
import numpy as np
import warnings 

warnings.filterwarnings('ignore')

df = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Join_Date": pd.to_datetime([
        "2022-01-10", "2022-02-15", "2022-03-20", "2022-04-05",
        "2022-05-12", "2022-06-18", "2022-07-22",
        "2022-08-30", "2022-09-14", "2022-10-01"
    ]),
    "Department": ["Sales", "HR", np.nan, "IT", "Finance", "Sales", np.nan, "IT", "Finance", "Sales"],
    "Age": [22, 25, np.nan, 29, 35, 28, 40, np.nan, 26, 55],
    "Salary": [25000, 30000, 28000, 32000, 150000, 31000, 40000, 29000, 27000, 500000],
    "Monthly_Spend": [8000, 9000, 8500, 10000, 12000, np.nan, 15000, 8700, 8900, 60000]
})

df

   ID  Join_Date Department   Age  Salary  Monthly_Spend
0   1 2022-01-10      Sales  22.0   25000         8000.0
1   2 2022-02-15         HR  25.0   30000         9000.0
2   3 2022-03-20        NaN   NaN   28000         8500.0
3   4 2022-04-05         IT  29.0   32000        10000.0
4   5 2022-05-12    Finance  35.0  150000        12000.0
5   6 2022-06-18      Sales  28.0   31000            NaN
6   7 2022-07-22        NaN  40.0   40000        15000.0
7   8 2022-08-30         IT   NaN   29000         8700.0
8   9 2022-09-14    Finance  26.0   27000         8900.0
9  10 2022-10-01      Sales  55.0  500000        60000.0

---------------

### **Filling Missing Values with Constants**
#### **For Numerical Data**

In [31]:
df["Age1"] = df["Age"].fillna(0)
df

   ID  Join_Date Department   Age  Salary  Monthly_Spend  Age1
0   1 2022-01-10      Sales  22.0   25000         8000.0  22.0
1   2 2022-02-15         HR  25.0   30000         9000.0  25.0
2   3 2022-03-20        NaN   NaN   28000         8500.0   0.0
3   4 2022-04-05         IT  29.0   32000        10000.0  29.0
4   5 2022-05-12    Finance  35.0  150000        12000.0  35.0
5   6 2022-06-18      Sales  28.0   31000            NaN  28.0
6   7 2022-07-22        NaN  40.0   40000        15000.0  40.0
7   8 2022-08-30         IT   NaN   29000         8700.0   0.0
8   9 2022-09-14    Finance  26.0   27000         8900.0  26.0
9  10 2022-10-01      Sales  55.0  500000        60000.0  55.0

#### **For Categorical Data**

In [32]:
df["Department1"] = df["Department"].fillna("Unknown")
df

   ID  Join_Date Department   Age  Salary  Monthly_Spend  Age1 Department1
0   1 2022-01-10      Sales  22.0   25000         8000.0  22.0       Sales
1   2 2022-02-15         HR  25.0   30000         9000.0  25.0          HR
2   3 2022-03-20        NaN   NaN   28000         8500.0   0.0     Unknown
3   4 2022-04-05         IT  29.0   32000        10000.0  29.0          IT
4   5 2022-05-12    Finance  35.0  150000        12000.0  35.0     Finance
5   6 2022-06-18      Sales  28.0   31000            NaN  28.0       Sales
6   7 2022-07-22        NaN  40.0   40000        15000.0  40.0     Unknown
7   8 2022-08-30         IT   NaN   29000         8700.0   0.0          IT
8   9 2022-09-14    Finance  26.0   27000         8900.0  26.0     Finance
9  10 2022-10-01      Sales  55.0  500000        60000.0  55.0       Sales

-------------------------------------------

### **Filling Missing Values with Mean, Median and Mode**

##### **This Method will be Used Only if dataset is not having outliers.**
- If it has outliers the mean will be moved towards Outlier.
- To calculate Mean: **Sum of All elements / Count of All Elements**

In [33]:
df["Monthly_Spend1"] = df["Monthly_Spend"].fillna(df["Monthly_Spend"].mean())
df

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000

##### **This Method Can be Used If the Datase is having outliers**
- First the data points are arranged in asceding or descending order.
- If dataset contains Odd Number of Elements **Middle data will be the Median**
- If dataset contains Even Number of Elements **Average of 2 Middle Elements will be the Median**

In [34]:
df["Department2"] = df["Department"].fillna(df["Department"].mode()[0])
df

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales

- Mode Can be Used for both **Numerical and Categorical Data**
- But majority of the times will be used for Categorical Data only.

---------------------------------

### **Filling Missing Values With Forward (Next) and Backward (Previous) Values**
- In some Time Series related dataset if we fill previous or next values that will be great in this situation we will use this methods.

#### **Forward Fill**

In [36]:
df["Monthly_Spend2"] = df["Monthly_Spend"].fillna(method = 'ffill')
df

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales,8000.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR,9000.0
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales,8500.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT,10000.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance,12000.0
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales,12000.0
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales,15000.0
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT,8700.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance,8900.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales,60000.0

#### **Backward Fill**

In [37]:
df["Monthly_Spend3"] = df["Monthly_Spend"].fillna(method = 'bfill')
df

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales,8000.0,8000.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR,9000.0,9000.0
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales,8500.0,8500.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT,10000.0,10000.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance,12000.0,12000.0
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales,12000.0,15000.0
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales,15000.0,15000.0
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT,8700.0,8700.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance,8900.0,8900.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales,60000.0,60000.0

----

### **Dropping Rows or Columns that has Contain Missing Values**

#### **Dropping Rows**
- **Example:** If I will be having one dataset which contains 1000 rows and 4 rows has missing values, then removing 4 rows will not make much differences, then we can remove those**
- If the 5% of row has missing values remove those.

#### **Default: Drop Rows that has any missing values**

In [40]:
df_clean = df.dropna(axis=0)
df_clean

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.0,Sales,8000.0,8000.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.0,HR,9000.0,9000.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.0,IT,10000.0,10000.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.0,Finance,12000.0,12000.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.0,Finance,8900.0,8900.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.0,Sales,60000.0,60000.0

#### **Drop Rows that has any missing values - Explicit**

In [42]:
df_clean = df.dropna(axis=0, how='any')
df_clean

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.0,Sales,8000.0,8000.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.0,HR,9000.0,9000.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.0,IT,10000.0,10000.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.0,Finance,12000.0,12000.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.0,Finance,8900.0,8900.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.0,Sales,60000.0,60000.0

#### **Drop Rows that has all values as missing values**

In [43]:
df_clean = df.dropna(axis=0, how='all')
df_clean

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales,8000.0,8000.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR,9000.0,9000.0
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales,8500.0,8500.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT,10000.0,10000.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance,12000.0,12000.0
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales,12000.0,15000.0
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales,15000.0,15000.0
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT,8700.0,8700.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance,8900.0,8900.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales,60000.0,60000.0

#### **Dropping Columns**
- If the dataset has some columns that contains 50 or more than 50% of the data are missing and it is not required for analysis remove those columns

#### **Default: Drop Columns with any missing values**

In [44]:
df_col_drop = df.dropna(axis=1)
df_col_drop

,ID,Join_Date,Salary,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,25000,22.0,Sales,8000.000000,Sales,8000.0,8000.0
1,2,2022-02-15,30000,25.0,HR,9000.000000,HR,9000.0,9000.0
2,3,2022-03-20,28000,0.0,Unknown,8500.000000,Sales,8500.0,8500.0
3,4,2022-04-05,32000,29.0,IT,10000.000000,IT,10000.0,10000.0
4,5,2022-05-12,150000,35.0,Finance,12000.000000,Finance,12000.0,12000.0
5,6,2022-06-18,31000,28.0,Sales,15566.666667,Sales,12000.0,15000.0
6,7,2022-07-22,40000,40.0,Unknown,15000.000000,Sales,15000.0,15000.0
7,8,2022-08-30,29000,0.0,IT,8700.000000,IT,8700.0,8700.0
8,9,2022-09-14,27000,26.0,Finance,8900.000000,Finance,8900.0,8900.0
9,10,2022-10-01,500000,55.0,Sales,60000.000000,Sales,60000.0,60000.0

#### **Drop Columns with any missing values - Explicit**

In [45]:
df_col_drop = df.dropna(axis=1, how='any')
df_col_drop

,ID,Join_Date,Salary,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,25000,22.0,Sales,8000.000000,Sales,8000.0,8000.0
1,2,2022-02-15,30000,25.0,HR,9000.000000,HR,9000.0,9000.0
2,3,2022-03-20,28000,0.0,Unknown,8500.000000,Sales,8500.0,8500.0
3,4,2022-04-05,32000,29.0,IT,10000.000000,IT,10000.0,10000.0
4,5,2022-05-12,150000,35.0,Finance,12000.000000,Finance,12000.0,12000.0
5,6,2022-06-18,31000,28.0,Sales,15566.666667,Sales,12000.0,15000.0
6,7,2022-07-22,40000,40.0,Unknown,15000.000000,Sales,15000.0,15000.0
7,8,2022-08-30,29000,0.0,IT,8700.000000,IT,8700.0,8700.0
8,9,2022-09-14,27000,26.0,Finance,8900.000000,Finance,8900.0,8900.0
9,10,2022-10-01,500000,55.0,Sales,60000.000000,Sales,60000.0,60000.0

#### **Drop Columns with all missing values**

In [46]:
df_col_drop = df.dropna(axis=1, how='all')
df_col_drop

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales,8000.0,8000.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR,9000.0,9000.0
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales,8500.0,8500.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT,10000.0,10000.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance,12000.0,12000.0
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales,12000.0,15000.0
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales,15000.0,15000.0
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT,8700.0,8700.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance,8900.0,8900.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales,60000.0,60000.0

### **Replacing Null Values**

In [48]:
import numpy as np
df["Replace1"] = df["Age"].replace(np.nan, 26.0)
df

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3,Replace1
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales,8000.0,8000.0,22.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR,9000.0,9000.0,25.0
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales,8500.0,8500.0,26.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT,10000.0,10000.0,29.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance,12000.0,12000.0,35.0
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales,12000.0,15000.0,28.0
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales,15000.0,15000.0,40.0
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT,8700.0,8700.0,26.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance,8900.0,8900.0,26.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales,60000.0,60000.0,55.0

### **Interpolation Method**
- If the dataset has the values that are linear and some value is missing values that time it can be used
- But if the dataset has sudden jumps it cannot be used
- Doesn't make sense for categorical data

In [49]:
df["Age2"] = df["Age"].interpolate(method = 'linear')
df

,ID,Join_Date,Department,Age,Salary,Monthly_Spend,Age1,Department1,Monthly_Spend1,Department2,Monthly_Spend2,Monthly_Spend3,Replace1,Age2
0,1,2022-01-10,Sales,22.0,25000,8000.0,22.0,Sales,8000.000000,Sales,8000.0,8000.0,22.0,22.0
1,2,2022-02-15,HR,25.0,30000,9000.0,25.0,HR,9000.000000,HR,9000.0,9000.0,25.0,25.0
2,3,2022-03-20,NaN,NaN,28000,8500.0,0.0,Unknown,8500.000000,Sales,8500.0,8500.0,26.0,27.0
3,4,2022-04-05,IT,29.0,32000,10000.0,29.0,IT,10000.000000,IT,10000.0,10000.0,29.0,29.0
4,5,2022-05-12,Finance,35.0,150000,12000.0,35.0,Finance,12000.000000,Finance,12000.0,12000.0,35.0,35.0
5,6,2022-06-18,Sales,28.0,31000,NaN,28.0,Sales,15566.666667,Sales,12000.0,15000.0,28.0,28.0
6,7,2022-07-22,NaN,40.0,40000,15000.0,40.0,Unknown,15000.000000,Sales,15000.0,15000.0,40.0,40.0
7,8,2022-08-30,IT,NaN,29000,8700.0,0.0,IT,8700.000000,IT,8700.0,8700.0,26.0,33.0
8,9,2022-09-14,Finance,26.0,27000,8900.0,26.0,Finance,8900.000000,Finance,8900.0,8900.0,26.0,26.0
9,10,2022-10-01,Sales,55.0,500000,60000.0,55.0,Sales,60000.000000,Sales,60000.0,60000.0,55.0,55.0

------------------------

### **If you remember only this decision flow, you’ll handle most cases well:**  </br>
**1. Check % of missing values.**
- If too high (>50%) in a column → drop the column.
- If very low (<5% rows) → consider dropping those rows. </br>

**2. Understand the column type & meaning.**
- Categorical: Use mode or a constant like "Unknown".
- Numerical: 
▪ Normal distribution? → Mean. </br>
▪ Skewed or has outliers? → Median. </br>
▪ Gradual change (time-series)? → Interpolation / forward fill. </br>

**3. Preserve data meaning.**
- Don’t just “fill to remove nulls” — think if the fill value makes sense in real life.

--------------------

### **To Check How Much values are missing in a column**

In [52]:
print(f"{(df.isnull().sum() / len(df)) * 100}")

ID                 0.0
Join_Date          0.0
Department        20.0
Age               20.0
Salary             0.0
Monthly_Spend     10.0
Age1               0.0
Department1        0.0
Monthly_Spend1     0.0
Department2        0.0
Monthly_Spend2     0.0
Monthly_Spend3     0.0
Replace1           0.0
Age2               0.0
dtype: float64

----------------------